status = [
    "Build and Test (1.14, darwin-amd64, macos-%)",
    "Build and Test (1.14, linux-aarch64, self-hosted, linux, ARM64)",
    "Build and Test (1.14, linux-amd64, ubuntu-%)",
    "Build and Test (1.14, linux-amd64, ubuntu-%, wasmer-%.tar.gz)",
    "Build and Test (1.14, windows-amd64, windows-%)",
    "Build and Test (1.15, darwin-amd64, macos-%)",
    "Build and Test (1.15, linux-aarch64, self-hosted, linux, ARM64)",
    "Build and Test (1.15, linux-amd64, ubuntu-%)",
    "Build and Test (1.15, linux-amd64, ubuntu-%, wasmer-%.tar.gz)",
    "Build and Test (1.15, windows-amd64, windows-%)"
]
required_approvals = 1
timeout_sec = 7200
delete_merged_branches = true 